---
- name: Install MySQL
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  sudo: yes
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start the MySQL service
  sudo: yes
  service: 
   name: mysql 
   state: started
   enabled: true

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
   name: root 
   host: "{{ item }}" 
   password: "{{ db_password }}"
   login_user: "{{ db_user }}" 
   login_password: "{{ db_root_password }}"
   check_implicit_admin: yes
   priv: "*.*:ALL,GRANT"
   with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

#   - name: Create Mysql configuration file
#  	template: src=my.cnf.j2 dest=/etc/my.cnf
#  	notify:
#   - restart mysql

#- name: Start Mysql Service

#    service: name=mysqld state=started enabled=yes

#- name: Create Application Database
#    mysql_db: name={{ dbname }} state=present

#- name: Create Application DB User
#    mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
