---
- name: install common apt packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - curl
  become: yes

- name: Set firewall default policy
  ufw: state=reset policy=reject

- name: Set firewall default policy
  ufw: state=enabled policy=reject

- name: Allow ssh
  ufw: rule=allow port=22 
